# Generated by Django 2.0.3 on 2018-10-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('filePath', models.CharField(max_length=100)),
                ('dataDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('serialNumberInserv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='SystemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.System'),
        ),
    ]
