# Generated by Django 2.0.3 on 2018-11-27 16:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('filePath', models.CharField(max_length=100)),
                ('dataDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('serialNumberInserv', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('tenants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='SystemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.System'),
        ),
    ]
