# Generated by Django 2.1.1 on 2018-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='recentDate',
            field=models.DateField(),
        ),
    ]
