# Generated by Django 2.0.3 on 2018-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='FileID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='system',
            name='serialNumberInserv',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
