# Generated by Django 2.0.3 on 2018-11-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
